import Head from 'next/head'
import Login from '../components/Login';
import Navbar from '../components/navbar'
// import { unstable_getServerSession } from 'next-auth';
import { getSession, signIn, useSession } from 'next-auth/react';
import { useEffect } from 'react';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Widgets from '../components/Widgets';

export default function Home() {
  const { data: session } = useSession();
  if(!session) return <Login/>;
  
  return (
    <div className='h-screen bg-gray-100 overflow-hidden' >
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* Header */}
      <Navbar/>
      <main className='flex' >
        {/* Sidebar */}
        <Sidebar></Sidebar>
        {/* Feed */}
        <Feed  ></Feed>
        {/* Widgets */}
        <Widgets></Widgets>
      </main>
    </div>
  )
}
export async function getServerSideProps(context){
  //Get the user
  const session = await getSession(
    context.req,
    context.res,
  );
  return {
    props:{
      session,
    }
  }
}